timezone: Japan
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-slate
title: prog-g
description: 岐阜大学プログラミングサークル
lang: ja

twitter:
  username: prog_g

email: mailto:programming.circle.gifu@gmail.com
