theme: jekyll-theme-slate
timezone: Japan
lang: ja

# slate theme settings
title: prog-g
description: 岐阜大学プログラミングサークル

# modified
twitter:
  label: "@prog-g"
  url: https://twitter.com/prog_g
email: mailto:programming.circle.gifu@gmail.com
